version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./.env.example
    volumes:
      - ./backend:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5173:5173"
    command: npm run dev -- --host

volumes:
  data:
    driver: local
